Portfolio/config/routes.rb
Rails.application.routes.draw do
  devise_for :models
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :projects
  resources :about, only: [:index]


root to: 'welcome#index'

end

Portfolio/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Portfolio/app/models/model.rb
class Model < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

Portfolio/app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

Portfolio/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

Portfolio/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
    @repos = Hubgit.get_repos
  end

end

Portfolio/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

Portfolio/app/helpers/about_helper.rb
module AboutHelper
end

Portfolio/app/helpers/application_helper.rb
module ApplicationHelper
end

Portfolio/app/helpers/projects_helper.rb
module ProjectsHelper
end

Portfolio/app/helpers/welcome_helper.rb
module WelcomeHelper
end

Portfolio/app/views/about/index.html.erb
  <div class="row">
    <div class="col-md-6">
      <%= image_tag("getro.jpeg", :id => "image") %>
    </div>
    <div class="col-md-6">
      <h1 id="dive" >The Original Plan</h1>
      <p>
        The plan was quite simple, obtain my bachelor's degree from the University of Florida and go on to complete a Juris Doctor degree at a prestigious law school. However, after completing the introductory computer science course from Harvard University (CS50) on a whim,  It dawned on me that a career in software development was the next best step in my professional development. I spent a full year learning the fundamentals of computer science by completing the FreeCodeCamp online bootcamp along with numerous MOOC Computer Science courses.
      </p>
      <div class="col-md-12">
        <h1 id="dive" >Inspiration</h1>
        <p>
          On a personal note, I am a lifelong learner  and I thoroughly enjoy the fact that I will constantly have to unlearn the outdated versions of certain programming languages and frameworks in order to stay abreast of the latest programming languages.  More importantly, I was drawn to the field due to its immense potential to solve some the most compelling challenges in this century.
        </p>
        <div class="col-md-12">
          <h1 id="dive">Outlook</h1>
          <p>
            I have a bachelor’s degree from the University of Florida (UF) and I have successfully completed the full-stack Ruby on Rails Mobile and Web development program at Epicodus. I am gungho to start applying my new skills to make this world a better place.
          </p>
        </div>
      </div>
    </div>
  </div>

Portfolio/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">Home</a>
    </div>
    <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav navbar-right">
          <li class="active"><%= link_to "Projects", projects_path %><span class="sr-only">(current)</span></li>
          <li><%= link_to "About", about_index_path %></li>
          <li><a href="/main">Admin</a></li>
        </ul>
    </div>
  </div>
</nav>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    <div class="container">
      <%= yield %>
    </div>

  </body>
</html>

Portfolio/app/views/projects/index.html.erb
<h1 id="dive">Projects</h1>

<% @repos.each do |repo| %>
<p >
  <%= link_to repo['name'], repo['html_url'] %>
</p>
<% end %>

Portfolio/app/views/welcome/index.html.erb
<h1 id="dive">My Time at Epicodus</h1>

<div class="row">
  <div class="col-md-12">
    <%= image_tag("getro2.png", :id => "image1") %>
  <div class="col-md-">
    <%= image_tag("eat.gif", :id => "image11") %>
  </div>
  <div class="">
    <%= image_tag("sleep.gif", :id => "image11") %>
  </div>
  </div>
</div>