webtext/config/routes.rb
Rails.application.routes.draw do
  resources :messages, :only => [:index, :new, :create, :show]
end

webtext/app/models/message.rb
class Message < ActiveRecord::Base
  before_create :send_sms

private

  def send_sms
    begin
      response = RestClient::Request.new(
        :method => :post,
        :url => "https://api.twilio.com/2010-04-01/Accounts/#{ENV['TWILIO_ACCOUNT_SID']}/Messages.json",
        :user => ENV['TWILIO_ACCOUNT_SID'],
        :password => ENV['TWILIO_AUTH_TOKEN'],
        :payload => { :Body => body,
                      :From => from,
                      :To => to }
      ).execute
    rescue RestClient::BadRequest => error
      message = JSON.parse(error.response)['message']
      errors.add(:base, message)
      throw(:abort)
    end
  end
end

webtext/app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def index
    @messages = Message.all
  end

  def show
    @message = Message.find(params[:id])
  end

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(message_params)
    if @message.save
      flash[:notice] = "Your message was sent!"
      redirect_to messages_path
    else
      render :new
    end
  end


private
  def message_params
    params.require(:message).permit(:to, :from, :body)
  end
end

webtext/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Webtext</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= flash[:notice] %>
    <%= yield %>
  </body>
</html>

webtext/app/views/messages/index.html.erb
<h1>Messages</h1>

<ul>
  <% @messages.each do |message| %>
    <li><%= link_to message.id, message_path(message)%></li>
  <% end %>
</ul>

<%= link_to "New message", new_message_path %>

webtext/app/views/messages/new.html.erb
<h1>New message</h1>

<% if @message.errors.any? %>
  <p>Something went wrong:</p>
  <ul>
    <% @message.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @message do |f| %>
  <%= f.label :to %>
  <%= f.text_field :to %>
  <%= f.label :from %>
  <%= f.text_field :from %>
  <%= f.label :body %>
  <%= f.text_field :body %>
  <%= f.submit %>
<% end %>